package com.qiu.munchee.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.file_name2
     *
     * @mbg.generated
     */
    private String fileName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.file_name1
     *
     * @mbg.generated
     */
    private String fileName1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.age
     *
     * @return the value of t_user.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.age
     *
     * @param age the value for t_user.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.file_name2
     *
     * @return the value of t_user.file_name2
     *
     * @mbg.generated
     */
    public String getFileName2() {
        return fileName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.file_name2
     *
     * @param fileName2 the value for t_user.file_name2
     *
     * @mbg.generated
     */
    public void setFileName2(String fileName2) {
        this.fileName2 = fileName2 == null ? null : fileName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.file_name1
     *
     * @return the value of t_user.file_name1
     *
     * @mbg.generated
     */
    public String getFileName1() {
        return fileName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.file_name1
     *
     * @param fileName1 the value for t_user.file_name1
     *
     * @mbg.generated
     */
    public void setFileName1(String fileName1) {
        this.fileName1 = fileName1 == null ? null : fileName1.trim();
    }
}