server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
    #实体类所做包
    type-aliases-package: com.qiu.munchee.entity